[package]
name = "encryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
rand = "^0.8.5"
pbkdf2 = "0.7.5"
serde_json = "1.0"